services:
  app:
    image: goapp:latest
    ports:
      - "9090:80" # Pour l'application Go
    volumes:
      - ./configdocker.json:/app/config.json # Point de montage pour le cache
      - ./docker/cache/:/app/cache/ # Point de montage pour le cache
      - ./docker/dl/:/app/dl/ # Point de montage pour les téléchargements
      - ./docker/db/:/app/db # Point de montage pour la base de données
    networks:
      - private_network
networks:
  private_network:
    driver: bridge
