services:
  app:
    image: goapp
    ports:
      - "80:80" # Pour l'application Go
    volumes:
      - ./config.json:/app/config.json # Point de montage pour le cache
      - ./cache/:/app/cache/ # Point de montage pour le cache
      - ./dl/:/app/dl/ # Point de montage pour les téléchargements
    networks:
      - private_network
networks:
  private_network:
    driver: bridge
